scriptfind:
	gcc find.c -lpthread -o find
	./find
scriptinterface:
	gcc interface.c -o interface
	./interface
scriptmemoryTest:
	gcc memoryTest.c -o memoryTest
	./memoryTest
sserver:
	gcc server.c -o server
	./server
sclient:
	gcc client.c -o client
	./client
stest:
	gcc test.c -o test
	./test
sfind2:
	gcc find2.c -lpthread -o find2
	./find2
scriptinterface2:
	gcc interface2.c -o interface2
	./interface2