scriptfind:
	gcc find.c -o find
	./find
scriptinterface:
	gcc interface.c -o interface
	./interface
scriptmemoryTest:
	gcc memoryTest.c -o memoryTest
	./memoryTest
sserver:
	gcc server.c -o server
	./server
sclient:
	gcc client.c -o client
	./client
stest:
	gcc test.c -o test
	./test